#!/bin/sh

set -eu

BASEDIR="$(dirname "$0")"

. "$BASEDIR/conf"

: "${KISS_CBUILD_ROOTFS:-}"
: "${KISS_CBUILD_SRCCACHE:=$BASEDIR/artifacts/src}"
: "${KISS_CBUILD_BINCACHE:=$BASEDIR/artifacts/bin}"
: "${KISS_CBUILD_REPODIR:-}"
: "${KISS_CBUILD_REPOS:-}"

KISS_PATH=""

mkdir -p "$KISS_CBUILD_SRCCACHE" "$KISS_CBUILD_BINCACHE"

for repo in $KISS_CBUILD_REPOS; do
    KISS_PATH="$KISS_PATH:/repos/$repo"
done

env -i bwrap \
	--tmpfs / \
	--unshare-all \
	--share-net \
	--ro-bind "$KISS_CBUILD_ROOTFS" /rootfs.tar \
	--bind "$KISS_CBUILD_SRCCACHE" /.cache/kiss/sources \
	--bind "$KISS_CBUILD_BINCACHE" /.cache/kiss/bin \
	--bind "$KISS_CBUILD_REPODIR" /repos \
	--ro-bind /usr/bin/busybox /busybox \
	--ro-bind "$BASEDIR/setup.sh" /setup.sh \
	--setenv KISS_PATH "$KISS_PATH" \
	--setenv CFLAGS "-march=x86-64 -mtune=generic -pipe -O2" \
	--setenv CXXFLAGS "-march=x86-64 -mtune=generic -pipe -O2" \
	--setenv MAKEFLAGS "-j$(nproc)" \
	--setenv PATH /usr/bin \
	--setenv LOGNAME root \
	--setenv HOME / \
	--uid 0 \
	--gid 0 \
	/busybox sh /setup.sh "${1:?No package provided}"
